"""Rendering an :class:`AuditReport` as a single self-contained web page.

One file, no assets, no CDN, no build step: the output is an ``.html`` a
business can email to their agency or open from a USB stick in three years. The
PDF is produced by the browser's own print pipeline behind a button, so there is
no headless-Chrome dependency in the tool and the PDF always matches what the
owner just looked at. ``@media print`` hides the chrome and forces page breaks
between sections.

**The page is split because the two readers want opposite things.** The owner
wants a grade, five bars, and the sentences their agent got wrong; anything more
and they stop reading. The IT team wants every metric, its basis, its sample
size, the per-call table and the rubric digest, and treats a missing denominator
as a bug. Writing one page for both produces a document neither finishes, so the
owner section leads and the technical appendix follows under its own heading.

Two things are marked visually rather than only in prose, because in a PDF a
caveat in body text is a caveat nobody reads: metrics an LLM judged, and metrics
that could not be measured at all.
"""

from __future__ import annotations

import html
from datetime import datetime

from simharness.reporting.schemas import (
    AuditReport,
    Category,
    CategoryScore,
    FactSource,
    Finding,
    Metric,
    MetricBasis,
    Severity,
)

__all__ = ["render_html"]

_CATEGORY_ORDER: tuple[Category, ...] = (
    Category.COMPLIANCE,
    Category.ADHERENCE,
    Category.RELIABILITY,
    Category.BUSINESS,
    Category.QUALITY,
)

_CATEGORY_BLURB: dict[Category, str] = {
    Category.COMPLIANCE: "Did it say anything untrue, or do anything it was told not to?",
    Category.ADHERENCE: "Did it follow your instructions, turn by turn?",
    Category.RELIABILITY: "Did it answer quickly, without silences or errors?",
    Category.BUSINESS: "Did calls end in bookings, and did callers get what they rang for?",
    Category.QUALITY: "Did it sound like a competent person handled the call?",
}

_SEVERITY_LABEL: dict[Severity, str] = {
    Severity.CRITICAL: "Critical",
    Severity.MAJOR: "Major",
    Severity.MINOR: "Minor",
    Severity.INFO: "Note",
}

_VERDICT_LABEL: dict[str, str] = {
    "pass": "Pass",
    "at_risk": "Needs attention",
    "fail": "Failing",
    "not_assessed": "Not assessed",
}


def render_html(report: AuditReport) -> str:
    """Render the whole audit as one standalone HTML document."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agent audit — {html.escape(report.business_name)}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="actions no-print">
  <button type="button" onclick="window.print()">Download PDF</button>
</div>
{_header(report)}
<main>
{_owner_section(report)}
{_technical_section(report)}
</main>
<footer>
  <p>Generated by SIMharness {html.escape(report.tool_version)} ·
     rubric {html.escape(report.rubric_id)} ({html.escape(report.rubric_digest)}) ·
     report {html.escape(report.report_id)}</p>
</footer>
</body>
</html>
"""


# --------------------------------------------------------------------------- #
# Header and owner section
# --------------------------------------------------------------------------- #


def _header(report: AuditReport) -> str:
    grade = report.grade
    return f"""<header>
  <div class="masthead">
    <div>
      <p class="eyebrow">AI agent audit</p>
      <h1>{html.escape(report.business_name or report.business_id)}</h1>
      <p class="period">{_period(report)} · {report.calls_analysed} calls ·
         {report.turns_analysed} turns</p>
    </div>
    <div class="grade grade-{_grade_class(grade.score)}">
      <span class="letter">{html.escape(grade.letter)}</span>
      <span class="score">{grade.score:.0f}<small>/100</small></span>
      <span class="verdict">{html.escape(grade.verdict)}</span>
    </div>
  </div>
  {_cap_banner(report)}
</header>"""


def _cap_banner(report: AuditReport) -> str:
    if not report.grade.capped_by:
        return ""
    why = (
        "A single critical finding limits the overall grade regardless of how the "
        "other categories scored."
        if "critical" in report.grade.capped_by
        else "A pattern of major findings limits the overall grade regardless of how "
        "the other categories scored."
    )
    return (
        '<p class="banner">Grade capped by '
        f"{html.escape(report.grade.capped_by)}. {why}</p>"
    )


def _owner_section(report: AuditReport) -> str:
    return f"""<section id="owner">
  <h2>For the business owner</h2>
  <p class="lede">{_headline(report)}</p>
  <div class="cards">{"".join(_card(c) for c in _ordered(report))}</div>
  {_findings_block(report)}
  {_actions_block(report)}
</section>"""


def _headline(report: AuditReport) -> str:
    critical = len(report.critical_findings)
    major = sum(1 for f in report.findings if f.severity is Severity.MAJOR)
    grade = report.grade

    if critical:
        lead = (
            f"Your agent made {critical} critical mistake{'s' if critical > 1 else ''} "
            f"across {report.calls_analysed} calls."
        )
    elif major:
        lead = (
            f"No critical mistakes, but {major} thing{'s' if major > 1 else ''} "
            "need attention."
        )
    else:
        lead = f"Nothing critical was found across {report.calls_analysed} calls."
    return f"{lead} Overall grade {html.escape(grade.letter)} — {html.escape(grade.rationale)}"


def _card(category: CategoryScore) -> str:
    score = category.score
    label = category.category.value.capitalize()
    blurb = _CATEGORY_BLURB[category.category]
    if score is None:
        return f"""<article class="card card-none">
  <h3>{label}</h3>
  <p class="blurb">{html.escape(blurb)}</p>
  <p class="card-score">Not assessed</p>
  <p class="card-note">{category.unavailable_metrics} metric(s) could not be
     measured from these logs.</p>
</article>"""
    return f"""<article class="card">
  <h3>{label}</h3>
  <p class="blurb">{html.escape(blurb)}</p>
  <p class="card-score">{score:.0f}<small>/100</small>
     <span class="pill pill-{_grade_class(score)}">
       {html.escape(_VERDICT_LABEL.get(category.verdict, category.verdict))}</span></p>
  <div class="bar"><div class="bar-fill bar-{_grade_class(score)}"
       style="width:{max(2.0, score):.1f}%"></div></div>
</article>"""


def _findings_block(report: AuditReport) -> str:
    """The owner sees the worst ten, quoted. Everything else is in the appendix.

    Quoting is the point: an owner cannot act on "hallucination rate 4%", but
    they can act on their agent telling a caller the deposit is fifty pounds.
    """
    shown = [f for f in report.findings if f.severity in (Severity.CRITICAL, Severity.MAJOR)][:10]
    if not shown:
        return (
            '<h3 class="section-heading">What went wrong</h3>'
            '<p class="empty">Nothing critical or major was found in these calls.</p>'
        )

    remaining = len(report.findings) - len(shown)
    more = (
        f'<p class="more">{remaining} further finding(s) in the technical appendix.</p>'
        if remaining > 0
        else ""
    )
    return f"""<h3 class="section-heading">What went wrong</h3>
<div class="findings">{"".join(_finding(f) for f in shown)}</div>
{more}"""


def _finding(finding: Finding) -> str:
    expected = (
        f'<p class="expected">Your published value: '
        f"<strong>{html.escape(finding.expected)}</strong></p>"
        if finding.expected
        else ""
    )
    judged = (
        '<span class="tag tag-judged">AI-judged</span>'
        if finding.basis == MetricBasis.JUDGED.value
        else ""
    )
    return f"""<article class="finding finding-{finding.severity.value}">
  <p class="finding-head">
    <span class="tag tag-{finding.severity.value}">
      {html.escape(_SEVERITY_LABEL[finding.severity])}</span>
    {judged}
    <span class="ref">call {html.escape(finding.call_id)}, turn {finding.turn_index}</span>
  </p>
  <blockquote>{html.escape(_truncate(finding.quote, 320))}</blockquote>
  <p class="why">{html.escape(finding.explanation)}</p>
  {expected}
</article>"""


def _actions_block(report: AuditReport) -> str:
    """Concrete next steps, derived from the report rather than boilerplate."""
    actions: list[str] = []

    critical = report.critical_findings
    if critical:
        calls = sorted({f.call_id for f in critical})[:5]
        actions.append(
            f"Listen back to {', '.join(html.escape(c) for c in calls)} — "
            "these calls contain a critical finding."
        )

    weakest = [c for c in report.categories if c.score is not None]
    if weakest:
        worst = min(weakest, key=lambda c: c.score or 0.0)
        if (worst.score or 0.0) < 85.0:
            actions.append(
                f"{worst.category.value.capitalize()} is the weakest category at "
                f"{worst.score:.0f}/100 — see the appendix for which metric pulled it down."
            )

    if report.fact_sheet.provider_error:
        actions.append(
            "We could not reach your website to fill the facts you did not supply, so "
            "those were not checked at all. Send us the missing facts, or ask us to "
            f"re-run. ({html.escape(report.fact_sheet.provider_error)})"
        )

    if report.fact_sheet.coverage < 1.0:
        scraped = sum(1 for f in report.fact_sheet.facts if f.source is FactSource.CONTEXT_DEV)
        if scraped:
            actions.append(
                f"{scraped} fact(s) were taken from your website rather than supplied by you. "
                "Confirm they are current, or send us the authoritative list."
            )

    for gap in report.gaps[:3]:
        actions.append(f"{html.escape(gap.label)}: {html.escape(gap.needed)}")

    if not actions:
        return ""
    items = "".join(f"<li>{action}</li>" for action in actions)
    return f'<h3 class="section-heading">What to do next</h3><ol class="actions-list">{items}</ol>'


# --------------------------------------------------------------------------- #
# Technical appendix
# --------------------------------------------------------------------------- #


def _technical_section(report: AuditReport) -> str:
    return f"""<section id="technical">
  <h2>Technical appendix</h2>
  <p class="lede">Every metric, its basis, and the sample it was computed over.
     Two audits are comparable only when the rubric digest matches.</p>
  {"".join(_metric_table(c) for c in _ordered(report))}
  {_calls_table(report)}
  {_gaps_table(report)}
  {_methodology(report)}
</section>"""


def _metric_table(category: CategoryScore) -> str:
    rows = "".join(_metric_row(m) for m in category.metrics)
    score = "—" if category.score is None else f"{category.score:.1f}/100"
    return f"""<h3 class="section-heading">{category.category.value.capitalize()} — {score}</h3>
<div class="table-wrap"><table>
  <thead><tr>
    <th>Metric</th><th>Value</th><th>Score</th><th>Weight</th>
    <th>Sample</th><th>Basis</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table></div>"""


_TIGHT_UNITS = frozenset({"%", "ms", "s"})


def _value(metric: Metric) -> str:
    """``4100ms`` and ``50%`` read as one token; ``0.5 per call`` needs the space."""
    if metric.value is None:
        return "—"
    unit = html.escape(metric.unit)
    separator = "" if not unit or unit in _TIGHT_UNITS or unit.startswith("/") else " "
    return f"{metric.value:g}{separator}{unit}"


def _metric_row(metric: Metric) -> str:
    if metric.basis is MetricBasis.UNAVAILABLE:
        value = '<span class="na">not available</span>'
        score = "—"
    else:
        value = _value(metric)
        score = f"{metric.score:.0f}" if metric.score is not None else "context only"

    note = f'<p class="metric-note">{html.escape(metric.note)}</p>' if metric.note else ""
    detail = (
        f'<p class="metric-detail">{html.escape(_detail_line(metric))}</p>'
        if metric.detail
        else ""
    )
    return f"""<tr>
  <td><strong>{html.escape(metric.label)}</strong>
      <code>{html.escape(metric.key)}</code>{note}{detail}</td>
  <td>{value}</td>
  <td>{score}</td>
  <td>{metric.weight:g}</td>
  <td>{metric.sample_size or "—"}</td>
  <td><span class="tag tag-{metric.basis.value}">{metric.basis.value}</span></td>
</tr>"""


def _detail_line(metric: Metric) -> str:
    return ", ".join(f"{key}: {value}" for key, value in metric.detail.items())


def _calls_table(report: AuditReport) -> str:
    if not report.call_summaries:
        return ""
    rows = "".join(
        f"""<tr>
  <td><code>{html.escape(s.call_id)}</code></td>
  <td>{_stamp(s.started_at)}</td>
  <td>{s.turns}</td>
  <td>{f"{s.duration_s:.0f}s" if s.duration_s is not None else "—"}</td>
  <td>{html.escape(s.outcome.value)}</td>
  <td>{s.findings}</td>
  <td>{s.critical_findings or "—"}</td>
</tr>"""
        for s in report.call_summaries
    )
    return f"""<h3 class="section-heading">Calls</h3>
<div class="table-wrap"><table>
  <thead><tr>
    <th>Call</th><th>Started</th><th>Turns</th><th>Duration</th>
    <th>Outcome</th><th>Findings</th><th>Critical</th>
  </tr></thead>
  <tbody>{rows}</tbody>
</table></div>"""


def _gaps_table(report: AuditReport) -> str:
    if not report.gaps:
        return ""
    rows = "".join(
        f"""<tr>
  <td><strong>{html.escape(g.label)}</strong><code>{html.escape(g.metric_key)}</code></td>
  <td>{html.escape(g.reason)}</td>
  <td>{html.escape(g.needed)}</td>
</tr>"""
        for g in report.gaps
    )
    return f"""<h3 class="section-heading">What this audit could not measure</h3>
<p class="empty">These are reported as unmeasured rather than estimated. Nothing below
   affected the grade in either direction.</p>
<div class="table-wrap"><table>
  <thead><tr><th>Metric</th><th>Why not</th><th>What would fix it</th></tr></thead>
  <tbody>{rows}</tbody>
</table></div>"""


def _methodology(report: AuditReport) -> str:
    sheet = report.fact_sheet
    supplied = sum(1 for f in sheet.facts if f.source is FactSource.BUSINESS_CONFIG)
    scraped = sum(1 for f in sheet.facts if f.source is FactSource.CONTEXT_DEV)
    absent = sum(1 for f in sheet.facts if f.source is FactSource.ABSENT)
    judge = html.escape(report.judge_model) if report.judge_model else "not used"

    facts = "".join(
        f"""<tr>
  <td>{html.escape(f.label)}<code>{html.escape(f.key)}</code></td>
  <td>{html.escape(f.value) or '<span class="na">absent</span>'}</td>
  <td><span class="tag tag-source">{html.escape(f.source.value)}</span></td>
</tr>"""
        for f in sheet.facts
    )

    return f"""<h3 class="section-heading">Methodology</h3>
<ul class="method">
  <li>Rubric <code>{html.escape(report.rubric_id)}</code>, digest
      <code>{html.escape(report.rubric_digest)}</code>. Thresholds are chosen by us and
      documented in <code>simharness/reporting/grading.py</code>.</li>
  <li>Fact sheet: {supplied} supplied by the business, {scraped} scraped from the web,
      {absent} unavailable.</li>
  <li>LLM judge: {judge}. Judged metrics are weighted at half a measured metric and
      can never cap the overall grade.</li>
  <li>Metrics whose logs lacked the necessary fields are excluded from the average
      rather than scored zero.</li>
</ul>
<div class="table-wrap"><table>
  <thead><tr><th>Fact</th><th>Value audited against</th><th>Source</th></tr></thead>
  <tbody>{facts}</tbody>
</table></div>"""


# --------------------------------------------------------------------------- #
# Small helpers
# --------------------------------------------------------------------------- #


def _ordered(report: AuditReport) -> list[CategoryScore]:
    lookup = {c.category: c for c in report.categories}
    return [lookup[c] for c in _CATEGORY_ORDER if c in lookup]


def _grade_class(score: float | None) -> str:
    if score is None:
        return "none"
    if score >= 85.0:
        return "good"
    if score >= 70.0:
        return "warn"
    return "bad"


def _period(report: AuditReport) -> str:
    if report.period_start and report.period_end:
        return f"{_stamp(report.period_start)} to {_stamp(report.period_end)}"
    if report.period_start:
        return _stamp(report.period_start)
    return f"generated {_stamp(report.generated_at)}"


def _stamp(value: datetime | None) -> str:
    return value.strftime("%Y-%m-%d %H:%M") if value else "—"


def _truncate(text: str, limit: int) -> str:
    collapsed = " ".join(text.split())
    return collapsed if len(collapsed) <= limit else collapsed[: limit - 1] + "…"


_CSS = """
:root {
  --ink: #14181f; --muted: #5b6472; --line: #e3e7ee; --bg: #f6f7f9;
  --good: #1f8a52; --warn: #b8710e; --bad: #c02b2b; --none: #8a93a2;
  --accent: #23407a;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--ink);
  font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial,
        sans-serif;
}
main, header, footer { max-width: 1000px; margin: 0 auto; padding: 0 32px; }
header { padding-top: 40px; }
.masthead {
  display: flex; justify-content: space-between; align-items: flex-start; gap: 32px;
  border-bottom: 3px solid var(--ink); padding-bottom: 20px;
}
.eyebrow {
  margin: 0; text-transform: uppercase; letter-spacing: .12em; font-size: 11px;
  font-weight: 700; color: var(--muted);
}
h1 { margin: 6px 0 4px; font-size: 30px; letter-spacing: -.02em; }
.period { margin: 0; color: var(--muted); font-size: 13px; }
.grade {
  display: grid; justify-items: center; min-width: 132px; padding: 14px 18px;
  border-radius: 10px; background: #fff; border: 2px solid var(--none);
}
.grade .letter { font-size: 44px; font-weight: 800; line-height: 1; }
.grade .score { font-size: 15px; font-weight: 600; margin-top: 4px; }
.grade .score small { color: var(--muted); font-weight: 400; }
.grade .verdict {
  font-size: 11px; text-transform: uppercase; letter-spacing: .08em; color: var(--muted);
  margin-top: 2px;
}
.grade-good { border-color: var(--good); } .grade-good .letter { color: var(--good); }
.grade-warn { border-color: var(--warn); } .grade-warn .letter { color: var(--warn); }
.grade-bad  { border-color: var(--bad); }  .grade-bad  .letter { color: var(--bad); }
.banner {
  margin: 16px 0 0; padding: 12px 14px; border-left: 4px solid var(--bad);
  background: #fdf0f0; font-size: 14px;
}
section { margin: 40px 0; }
h2 {
  font-size: 13px; text-transform: uppercase; letter-spacing: .14em; color: var(--accent);
  border-bottom: 1px solid var(--line); padding-bottom: 8px; margin-bottom: 16px;
}
.lede { font-size: 17px; line-height: 1.5; margin: 0 0 24px; }
.section-heading { font-size: 15px; margin: 32px 0 12px; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; }
.card { background: #fff; border: 1px solid var(--line); border-radius: 8px; padding: 14px; }
.card h3 { margin: 0 0 4px; font-size: 14px; }
.blurb { margin: 0 0 10px; font-size: 12px; color: var(--muted); line-height: 1.4; }
.card-score { margin: 0 0 8px; font-size: 26px; font-weight: 700; }
.card-score small { font-size: 13px; color: var(--muted); font-weight: 400; }
.card-none .card-score { font-size: 15px; color: var(--none); font-weight: 600; }
.card-note { margin: 0; font-size: 12px; color: var(--muted); }
.bar { height: 6px; background: var(--line); border-radius: 3px; overflow: hidden; }
.bar-fill { height: 100%; }
.bar-good { background: var(--good); } .bar-warn { background: var(--warn); }
.bar-bad { background: var(--bad); }
.pill {
  font-size: 10px; text-transform: uppercase; letter-spacing: .06em; padding: 2px 7px;
  border-radius: 10px; vertical-align: middle; margin-left: 6px; color: #fff;
}
.pill-good { background: var(--good); } .pill-warn { background: var(--warn); }
.pill-bad { background: var(--bad); } .pill-none { background: var(--none); }
.findings { display: grid; gap: 10px; }
.finding {
  background: #fff; border: 1px solid var(--line); border-left: 4px solid var(--none);
  border-radius: 6px; padding: 12px 14px;
}
.finding-critical { border-left-color: var(--bad); }
.finding-major { border-left-color: var(--warn); }
.finding-head { margin: 0 0 8px; display: flex; align-items: center; gap: 8px; }
.finding blockquote {
  margin: 0 0 8px; padding: 8px 12px; background: var(--bg); border-radius: 4px;
  font-style: italic;
}
.why, .expected { margin: 0; font-size: 13px; color: var(--muted); }
.expected { margin-top: 4px; }
.tag {
  font-size: 10px; text-transform: uppercase; letter-spacing: .06em; font-weight: 700;
  padding: 2px 7px; border-radius: 3px; background: var(--line); color: var(--muted);
}
.tag-critical { background: var(--bad); color: #fff; }
.tag-major { background: var(--warn); color: #fff; }
.tag-judged { background: #6b4fbb; color: #fff; }
.tag-measured { background: #e7f1ea; color: var(--good); }
.tag-unavailable { background: #eceef2; color: var(--none); }
.tag-source { background: #eef2fa; color: var(--accent); }
.ref { font-size: 12px; color: var(--muted); margin-left: auto; }
.actions-list { margin: 0; padding-left: 20px; }
.actions-list li { margin-bottom: 6px; }
.empty, .more { color: var(--muted); font-size: 13px; }
table { width: 100%; border-collapse: collapse; background: #fff; font-size: 13px; }
.table-wrap { overflow-x: auto; }
@media print { .table-wrap { overflow-x: visible; } }
th, td { text-align: left; padding: 9px 10px; border-bottom: 1px solid var(--line);
         vertical-align: top; }
th { font-size: 11px; text-transform: uppercase; letter-spacing: .06em; color: var(--muted); }
td code { display: block; font-size: 11px; color: var(--muted); }
.metric-note, .metric-detail { margin: 4px 0 0; font-size: 12px; color: var(--muted); }
.na { color: var(--none); font-style: italic; }
.method { font-size: 13px; color: var(--muted); margin-bottom: 16px; }
.actions { max-width: 1000px; margin: 0 auto; padding: 20px 32px 0; text-align: right; }
.actions button {
  background: var(--accent); color: #fff; border: 0; border-radius: 6px;
  padding: 9px 16px; font-size: 14px; font-weight: 600; cursor: pointer;
}
footer { padding: 24px 32px 48px; color: var(--muted); font-size: 12px; }
@media print {
  body { background: #fff; }
  .no-print { display: none !important; }
  main, header, footer { max-width: none; padding: 0; }
  #technical { page-break-before: always; }
  .card, .finding, table, .banner { break-inside: avoid; }
  h2, .section-heading { break-after: avoid; }
  @page { margin: 16mm; }
}
"""
